### ISSUE TITLE
When we bump a version number, also bump the example

### ISSUE THREAD

**Issue by vielmetti** [fog/fog-packet#15]
Every time the version number gets bumped, we should also bump the example in the docs.

As seen in #14  by @jeefy .

**Comment by edevenport** [comment]
@vielmetti - We can update the documentation to demonstrate installing the gem from rubygems.org (`gem install fog-packet`). No version will be necessary as it will pull the latest in this case.

I suppose it doesn't hurt to still include an example of building the package from source in which case the version would still be specified. Would you like the version still maintained in the README or could we use a generic placeholder instead? For example:

**Comment by vielmetti** [comment]
Updating the docs to point at `gem install fog-packet` sounds like a win.

@edevenport - I have a weak preference for putting the current version number into the README, just so that detail is exposed on the front page of the repo and so we are ready to revisit the docs every time we bump a release.

**Comment by edevenport** [comment]
@vielmetti - Thank you for the feedback. I opened PR #16 that extends the README by including the common installation instructions similar to other providers, includes the package build details, and mentions the environment variable support for the token. Let me know if the updates look good and we can merge it.

**Comment by edevenport** [comment]
I have merged PR #16 which extends the README and includes the version. We also added integration to travis-ci and added some badges to the README.
