### ISSUE TITLE
Unnecessary output when retrieving SSH keys

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#19]
`> connection.ssh_keys.map{ |k| k.id }`
Expected:
```
=> ["some_key_id"]
```
Actual:
```
""
""
=> ["some_key_id"]
```
I guess there is no need in empty lines during execution.

**Comment by edevenport** [comment]
@dmitryshagin This was probably some lingering debug code. It has been removed and merged. Would you like a new release tagged?

**Comment by dmitryshagin** [comment]
Thanks. I think it's to minor to release.

**Comment by edevenport** [comment]
Agreed. Thanks for reporting the issue.
