### ISSUE TITLE
Lack of Device#ssh

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#22]
Would be great to have `Device#ssh` method, similar to `Compute#ssh` (https://github.com/fog/fog-core/blob/73e2784c8f852f2bf1a44e12b72e8430e957d444/lib/fog/compute/models/server.rb#L83).
By the way, is there any reason why `Device` does not inherit from `Compute`?

**Comment by jasmingacic** [comment]
Device is part of the Compute module -> https://github.com/fog/fog-packet/blob/master/lib/fog/compute/packet/models/device.rb#L1-L5.

Packet ssh_keys are a feature that can be created, destroyed, updated and retrieved. 
Compute#ssh is Fog core feature that should work out of the box.

**Comment by dmitryshagin** [comment]
That's not about `ssh_keys`, but about executing ssh commands on a server.
As far as `Device` is not inherited from Fog's `Server` it lacks this functionality. Like ssh'ing or scp'ing.

**Comment by edevenport** [comment]
@jasmingacic I agree with @dmitryshagin that this would be a good feature to implement. Our `Device` class would need to inherit the `Server` class. I'm not sure if we will need to adjust any of the `Server` methods to retrieve the public IP address? I don't think it would take too long to implement.

**Comment by edevenport** [comment]
@dmitryshagin We have merged the proposed change into master. Would you be able to [build the module](https://github.com/fog/fog-packet#build) from master and confirm it behaves as expected? Once this and the other latest changes are confirmed, we can tag a release.

**Comment by dmitryshagin** [comment]
LGTM, thanks.
