### ISSUE TITLE
Design of destroying snapshots

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#25]
The way we destroy snapshots is really odd.
`snapshot.destroy(volume_id, snapshot_id)` looks very weird. Why should one send `volume_id` while removing snapshot? `Snapshot` should know it's volume_id despite being encoded as a href.

**Comment by dmitryshagin** [comment]
Yep, but in this case we are not going to remove all snapshots. Just one.
My monkeypatch looks like this:
```
module Fog::Compute
  class Packet::Snapshot
    def destroy
      requires :id

      volume_id = volume["href"].split("/")[-1]
      response = service.delete_snapshot(volume_id, id)
      true if response.status == 204
    end
  end
end
```

So I'm passing both ID's - just don't make users pass them later in the code. Why should I if we already have all the data required inside an object.

**Comment by jasmingacic** [comment]
That makes sense.

**Comment by edevenport** [comment]
@dmitryshagin is right. Once we have the snapshot object, we should be able to `destroy` that object without any further parameters. This is normal Fog behavior.

@jasmingacic - Go ahead and implement this.

**Comment by edevenport** [comment]
@dmitryshagin We have merged the proposed change into master. Would you be able to [build the module](https://github.com/fog/fog-packet#build) from master and confirm it behaves as expected? Once this and the other latest changes are confirmed, we can tag a release.

**Comment by dmitryshagin** [comment]
LGTM, thanks.
