### ISSUE TITLE
Obtaining device state within the same `device` instance

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#7]
Actual behavior:
```
compute = Fog::Compute::Packet.new(packet_token: packet_token)
server = compute.devices.create(opts)
```
<wait for several minutes, ensure that server is running via GUI>

```
compute.devices.get(server.id).state
```
Returns nils. And returns valid state in several minutes after GUI tells me that everything is already running. How long can be the gap between API and GUI responses?

And obtaining updated state from instance of `server` looks impossible:
```
server.reload
server.state => "queued"
```

Expected:
Having an ability to get updated state without making explicit request, in the same instance. Maybe something like: `server.wait_for { server.active? }` (Google has something similar).

**Comment by edevenport** [comment]
Hello @dmitryshagin - the implementation of the `wait_for` was not yet completed when you were testing. It has now been implemented and it should be working in a familiar Fog style now:

```
device = compute.devices.create(:project_id => project.id, :facility => "ewr1", :plan => "baremetal_0", :hostname => "node01", :operating_system => "coreos_stable")
...
irb(main):051:0> device.state 
=> "queued"
irb(main):052:0> device.wait_for { ready? }
=> {:duration=>319.292766756}
irb(main):053:0> device.state
=> "active"
```

**Comment by vielmetti** [comment]
Hi @dmitryshagin - can you test this and see if it not addresses this issue? thanks!

**Comment by dmitryshagin** [comment]
That's better
```
server.wait_for { ready? }
=> {:duration=>311.204385}
```
`server.state` is now also changing after `server.reload`
Thanks!
